server:
  port: 8094
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            -  Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: EMPLOYEE-SERVICE
                fallbackuri: forward:/empServiceFallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            -  Path=/departments/**  
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallback
                           
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000        
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream                
        
eureka:
  client:
    register-with-eureka:  true
    fetch-registry:  true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost    